config/routes.rb
HowTo::Application.routes.draw do

  resources :alcohols do
    resources :steps
  end

  root to: 'alcohols#index'

end

app/models/alcohol.rb
class Alcohol < ActiveRecord::Base
  has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :alcohol
end

app/controllers/alcohols_controller.rb
class AlcoholsController < ApplicationController
  before_action :set_alcohol, only: [:show, :edit, :update, :destroy]

  # GET /alcohols
  # GET /alcohols.json
  def index
    @alcohols = Alcohol.all
  end

  # GET /alcohols/1
  # GET /alcohols/1.json
  def show
  end

  # GET /alcohols/new
  def new
    @alcohol = Alcohol.new
  end

  # GET /alcohols/1/edit
  def edit
  end

  # POST /alcohols
  # POST /alcohols.json
  def create
    @alcohol = Alcohol.new(alcohol_params)

    respond_to do |format|
      if @alcohol.save
        format.html { redirect_to @alcohol, notice: 'Alcohol was successfully created.' }
        format.json { render action: 'show', status: :created, location: @alcohol }
      else
        format.html { render action: 'new' }
        format.json { render json: @alcohol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alcohols/1
  # PATCH/PUT /alcohols/1.json
  def update
    respond_to do |format|
      if @alcohol.update(alcohol_params)
        format.html { redirect_to @alcohol, notice: 'Alcohol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @alcohol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alcohols/1
  # DELETE /alcohols/1.json
  def destroy
    @alcohol.destroy
    respond_to do |format|
      format.html { redirect_to alcohols_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alcohol
      @alcohol = Alcohol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alcohol_params
      params.require(:alcohol).permit(:name, :decsription, :ingredients)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  before_filter :get_alcohol
  # GET /steps
  # GET /steps.json
  def index
    @steps = @alcohol.steps
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = @alcohol.steps.find(params[:id])
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = @alcohol.steps.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to [@alcohol,@step], notice: 'Step was successfully created.' }
        format.json { render json: [@alcohol, @step],
                              status: :created,
                              location: [@alcohol, @step] }
      else
        format.html { render action: 'new' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to [@alcohol,@step], notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to alcohol_steps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:step_number, :description)
    end

    def get_alcohol
      @alcohol = Alcohol.find(params[:alcohol_id])
    end
end

app/helpers/alcohols_helper.rb
module AlcoholsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/alcohols/_form.html.erb
<%= form_for(@alcohol) do |f| %>
  <% if @alcohol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alcohol.errors.count, "error") %> prohibited this alcohol from being saved:</h2>

      <ul>
      <% @alcohol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :decsription %><br>
    <%= f.text_area :decsription %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alcohols/edit.html.erb
<h1>Editing alcohol</h1>

<%= render 'form' %>

<%= link_to 'Show', @alcohol %> |
<%= link_to 'Back', alcohols_path %>

app/views/alcohols/index.html.erb
<h1>Listing alcohols</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Decsription</th>
      <th>Ingredients</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @alcohols.each do |alcohol| %>
      <tr>
        <td><%= alcohol.name %></td>
        <td><%= alcohol.decsription %></td>
        <td><%= alcohol.ingredients %></td>

        <td><%= link_to 'Show', alcohol %></td>
        <td><%= link_to 'Edit', edit_alcohol_path(alcohol) %></td>
        <td><%= link_to 'Destroy', alcohol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alcohol', new_alcohol_path %>

app/views/alcohols/new.html.erb
<h1>New alcohol</h1>

<%= render 'form' %>

<%= link_to 'Back', alcohols_path %>

app/views/alcohols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alcohol.name %>
</p>

<p>
  <strong>Decsription:</strong>
  <%= @alcohol.decsription %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @alcohol.ingredients %>
</p>

<%= link_to 'Edit', edit_alcohol_path(@alcohol) %> |
<%= link_to 'Back', alcohols_path %>
<%= link_to 'Steps', alcohol_steps_path(@alcohol) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowTo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for([@alcohol, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step_number %><br>
    <%= f.number_field :step_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', [@alcohol, @step] %> |
<%= link_to 'Back', alcohol_steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Step number</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.step_number %></td>
        <td><%= step.description %></td>
        <td><%= link_to 'Show', [@alcohol, step] %></td>
        <td><%= link_to 'Edit', edit_alcohol_step_path(@alcohol, step) %></td>
        <td><%= link_to 'Destroy', [@alcohol,step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_alcohol_step_path(@alcohol) %>
<%= link_to 'Main Alcohol', alcohol_path(@alcohol) %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', alcohol_steps_path(@alcohol) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Step number:</strong>
  <%= @step.step_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @step.description %>
</p>

<%= link_to 'Edit', edit_alcohol_step_path(@alcohol, @step) %> |
<%= link_to 'Back', alcohol_steps_path %>